import 'core-js/es6';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import '@angular/common';
import '@angular/compiler';
import '@angular/core';
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import 'redux'
import 'redux-logger'
